# Generated by Django 5.2.1 on 2025-06-25 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='ocr_files/')),
                ('extracted_text', models.TextField()),
                ('detected_language', models.CharField(max_length=10)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cropprediction',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropprediction',
            name='language_detected',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cropprediction',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ocr', 'OCR Extraction')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='cropprediction',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
